### ISSUE TITLE
Release 2.99 and 3.0.0 ALPHA

### ISSUE THREAD

**Issue by xaviershay** [rspec/rspec-core#1136]
- [x] Merge #1089 or decide it's out for the alpha. @JonRowe [@xaviershay - it's out]
- [x] Finish ordering API deprecations #1092 @myronmarston 
- [x] New release of `rspec-autotest`. _??_
- [x] New release of `rspec-its`. _??_
- [x] New release of `rspec-collection_matchers`. @myronmarston (though hopefully can delegate to Hugo)
- [x] Double check builds are green. _??_
- [x] Bump version numbers in source. _??_
- [x] Double check changelog is nice. @xaviershay
- [x] Build and sign gems #783 @myronmarston 
- [x] Update GH milestones to reflect reality @xaviershay
- [x] Sanity check those gems against some of our existing projects. (Post results to comments.) _All_
- [x] Push to rubygems @myronmarston 
- [x] Announce on twitter (rspec account) @myronmarston 

"All gems" refers to `rspec-core`, `rspec-mocks`, `rspec-expectations`, and `rspec-rails`.
